name: 'Screenshot Action'
description: Takes a screenshot of a URL and posts it on the associated pull request'
inputs:
  url:
    description: 'The URL to capture a screenshot of'
    required: true
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - '${{ inputs.url }}'